In [1]:
import numpy as np
import pandas as pd
import pandas_profiling 
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Repository-DataSets/master/Regression/Daily%20Demand%20Forecasting%20Orders.csv')

In [3]:
data

,Unnamed: 0,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
0,0,1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793,539.577
1,1,1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679,224.675
2,2,1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947,129.412
3,3,2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423,317.120
4,4,2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257,210.517
5,5,2,4,110.925,96.360,30.792,50.704,125.868,79.000,52042,8773,47522,24966,207.364
6,6,2,5,144.124,118.919,43.304,66.371,153.368,0.000,46573,33597,48269,20973,263.043
7,7,2,6,119.379,113.870,38.584,85.961,124.413,15.709,35033,26278,56665,18502,248.958
8,8,3,2,218.856,124.381,33.973,148.274,162.044,1.054,66612,19461,103376,10458,344.291
9,9,3,3,146.518,101.045,36.399,43.306,168.723,865.000,58224,7742,82395,11948,248.428
10,10,3,4,178.433,102.793,45.706,111.036,124.678,194.000,47046,17299,108719,15560,281.420
11,11,3,5,145.865,91.180,43.851,66.277,133.440,6.523,66910,17768,36693,29046,243.568
12,12,3,6,170.566,114.412,43.339,136.434,128.405,23.200,32529,34002,78153,31949,308.178
13,13,4,2,220.343,141.406,46.241,120.865,196.296,1.653,34878,32905,117137,29188,363.402
14,14,4,3,193.768,141.854,56.519,136.709,143.644,1.250,57858,23956,101048,30134,336.872
15,15,4,4,122.736,124.256,56.167,78.101,112.724,0.000,52321,10046,62799,24233,246.992
16,16,4,5,144.051,158.408,51.660,92.272,164.948,6.421,47167,6440,91784,15973,308.880
17,17,4,6,105.415,108.688,47.717,71.474,113.935,19.023,42737,26020,27873,17600,233.126
18,18,5,2,240.660,163.720,59.135,157.681,187.564,0.000,39273,32917,155617,9203,404.380
19,19,1,3,131.067,166.649,90.476,80.509,127.575,844.000,60543,19141,78378,73839,298.560
20,20,1,4,130.129,98.927,42.904,43.962,142.383,193.000,54760,9163,29874,46992,229.249
21,21,1,5,123.286,103.551,47.331,72.444,116.529,9.467,48732,21196,47793,47574,236.304
22,22,1,6,190.816,87.629,32.077,127.358,137.739,18.729,46368,36798,92701,31098,297.174
23,23,2,2,266.741,141.437,58.721,139.034,211.646,1.223,58081,43333,135314,29716,409.401
24,24,2,3,123.143,106.083,36.017,75.813,119.205,1.809,45340,22109,55584,29803,231.035
25,25,2,4,148.139,85.310,35.576,79.997,123.253,5.377,59686,14188,67617,32319,238.826
26,26,2,5,118.552,100.417,54.401,75.613,105.584,16.629,40423,24682,47563,35314,235.598
27,27,2,6,146.959,95.153,37.656,59.907,144.549,0.000,50908,45733,43930,28998,242.112
28,28,3,2,299.770,133.375,57.810,236.248,196.732,57.645,71772,57756,159373,29160,490.790
29,29,3,3,151.341,131.788,43.359,89.382,156.916,6.528,53573,42638,62732,32386,289.657
30,30,3,4,206.206,92.160,45.555,148.718,104.186,93.000,49110,36904,126632,33237,298.459
31,31,3,5,170.868,131.463,45.550,120.548,157.505,21.272,42534,79556,50433,36483,323.603
32,32,4,3,435.304,181.149,67.884,267.342,281.227,0.000,64867,210508,177229,30514,616.453
33,33,4,4,235.106,110.874,70.376,154.242,121.417,55.000,23257,163452,63699,33805,346.035
34,34,4,5,168.179,125.119,71.068,100.544,136.033,14.347,28072,95989,50763,55445,307.645
35,35,4,6,172.783,77.371,64.137,109.062,80.648,3.693,46321,66498,61593,31625,253.847
36,36,5,2,381.768,140.041,118.178,260.632,152.134,9.135,34236,194216,136035,47601,530.944
37,37,5,3,221.438,111.392,51.199,124.660,157.500,529.000,39964,136119,66745,31031,333.359
38,38,5,4,193.957,111.859,47.002,99.892,159.462,540.000,59179,94460,54772,34616,306.356
39,39,1,6,275.076,121.697,109.888,131.165,175.777,20.057,37906,138536,85378,14020,416.830
40,40,2,2,252.298,150.708,77.388,154.863,182.936,12.181,32133,69093,169088,12516,415.187
41,41,2,3,165.472,102.530,46.295,96.870,124.837,0.000,48458,43112,72840,11304,268.002
42,42,2,4,126.030,108.055,53.366,69.150,111.987,418.000,42201,13736,70191,16710,234.503
43,43,2,5,112.246,106.641,47.399,77.610,109.715,15.837,35316,25876,38646,13989,234.724
44,44,2,6,123.302,94.315,48.081,72.826,109.157,12.447,43284,30138,52112,12632,230.064
45,45,3,2,187.810,167.455,59.042,130.098,168.254,2.129,37817,36445,103567,10443,357.394
46,46,3,3,119.863,139.383,44.809,99.072,115.365,0.000,54584,17242,59231,12543,259.246
47,47,3,4,127.805,114.813,39.025,110.740,94.470,1.617,33366,21103,84558,16683,244.235
48,48,3,5,120.629,112.703,39.600,240.922,122.085,169.275,37387,20246,63778,13886,402.607
49,49,3,6,130.465,105.273,57.467,88.462,109.132,19.323,27200,41713,59513,12260,255.061
50,50,4,2,222.282,120.324,41.418,135.189,165.999,0.000,39446,29290,154144,10811,342.606
51,51,4,3,150.257,116.959,34.193,115.536,118.911,1.424,51346,19782,89704,12182,268.640
52,52,4,4,96.494,87.294,32.653,81.576,74.372,4.813,34631,22420,49644,15390,188.601
53,53,4,5,89.526,99.756,51.985,51.930,98.107,12.740,31850,32150,21573,13807,202.022
54,54,4,6,134.425,79.084,36.748,71.353,105.408,0.000,33970,28701,65199,11023,213.509
55,55,5,2,158.716,158.133,59.131,92.639,165.079,0.000,32027,33282,128269,9287,316.849
56,56,5,3,150.784,133.069,54.224,115.746,116.442,2.559,51235,34421,87708,11354,286.412
57,57,5,4,193.534,109.639,58.378,142.382,102.687,274.000,28364,88404,91367,15003,303.447
58,58,5,5,196.555,108.395,76.763,96.478,131.709,0.000,37011,109931,50112,12957,304.950
59,59,5,6,192.116,121.106,107.568,121.152,103.180,18.678,27328,108072,56015,10690,331.900

In [4]:
data.isna().sum()

Unnamed: 0                                                            0
Week of the month (first week, second, third, fourth or fifth week    0
Day of the week (Monday to Friday)                                    0
Non-urgent order                                                      0
Urgent order                                                          0
Order type A                                                          0
Order type B                                                          0
Order type C                                                          0
Fiscal sector orders                                                  0
Orders from the traffic controller sector                             0
Banking orders (1)                                                    0
Banking orders (2)                                                    0
Banking orders (3)                                                    0
Target (Total orders)                                                 0
dtype: int64

In [5]:
data['Week of the month (first week, second, third, fourth or fifth week'].unique()

array([1, 2, 3, 4, 5])

In [7]:
data['Day of the week (Monday to Friday)'].unique()

array([4, 5, 6, 2, 3])

In [8]:
data.head()

,Unnamed: 0,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
0,0,1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793,539.577
1,1,1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679,224.675
2,2,1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947,129.412
3,3,2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423,317.120
4,4,2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257,210.517

In [9]:
data.tail()

,Unnamed: 0,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
55,55,5,2,158.716,158.133,59.131,92.639,165.079,0.000,32027,33282,128269,9287,316.849
56,56,5,3,150.784,133.069,54.224,115.746,116.442,2.559,51235,34421,87708,11354,286.412
57,57,5,4,193.534,109.639,58.378,142.382,102.687,274.000,28364,88404,91367,15003,303.447
58,58,5,5,196.555,108.395,76.763,96.478,131.709,0.000,37011,109931,50112,12957,304.950
59,59,5,6,192.116,121.106,107.568,121.152,103.180,18.678,27328,108072,56015,10690,331.900

In [10]:
data.describe()

,Unnamed: 0,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,29.500000,3.016667,4.033333,172.554933,118.920850,52.112217,109.229850,139.531250,77.396133,44504.350000,46640.833333,79401.483333,23114.633333,300.873317
std,17.464249,1.282102,1.401775,69.505788,27.170929,18.829911,50.741388,41.442932,186.502470,12197.905134,45220.736293,40504.420041,13148.039829,89.602041
min,0.000000,1.000000,2.000000,43.651000,77.371000,21.826000,25.125000,74.372000,0.000000,11992.000000,3452.000000,16411.000000,7679.000000,129.412000
25%,14.750000,2.000000,3.000000,125.348000,100.888000,39.456250,74.916250,113.632250,1.243250,34994.250000,20130.000000,50680.500000,12609.750000,238.195500
50%,29.500000,3.000000,4.000000,151.062500,113.114500,47.166500,99.482000,127.990000,7.831500,44312.000000,32527.500000,67181.000000,18011.500000,288.034500
75%,44.250000,4.000000,5.000000,194.606500,132.108250,58.463750,132.171000,160.107500,20.360750,52111.750000,45118.750000,94787.750000,31047.750000,334.237250
max,59.000000,5.000000,6.000000,435.304000,223.270000,118.178000,267.342000,302.448000,865.000000,71772.000000,210508.000000,188411.000000,73839.000000,616.453000

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 14 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Unnamed: 0                                                          60 non-null     int64
 1   Week of the month (first week, second, third, fourth or fifth week  60 non-null     int64
 2   Day of the week (Monday to Friday)                                  60 non-null     int64
 3   Non-urgent order                                                    60 non-null     float64
 4   Urgent order                                                        60 non-null     float64
 5   Order type A                                                        60 non-null     float64
 6   Order type B                                                        60 non-null     float64
 7   Order type C                                                        60 non-null     float64
 8   Fiscal sector orders                                                60 non-null     float64
 9   Orders from the traffic controller sector                           60 non-null     int64
 10  Banking orders (1)                                                  60 non-null     int64
 11  Banking orders (2)                                                  60 non-null     int64
 12  Banking orders (3)                                                  60 non-null     int64
 13  Target (Total orders)                                               60 non-null     float64
dtypes: float64(7), int64(7)
memory usage: 6.7 KB

In [12]:
data.shape

(60, 14)

In [13]:
data.columns

Index(['Unnamed: 0',
       'Week of the month (first week, second, third, fourth or fifth week',
       'Day of the week (Monday to Friday)', 'Non-urgent order',
       'Urgent order', 'Order type A', 'Order type B', 'Order type C',
       'Fiscal sector orders', 'Orders from the traffic controller sector',
       'Banking orders (1)', 'Banking orders (2)', 'Banking orders (3)',
       'Target (Total orders)'],
      dtype='object')

In [15]:
data.drop('Unnamed: 0',axis=1)

,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
0,1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793,539.577
1,1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679,224.675
2,1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947,129.412
3,2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423,317.120
4,2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257,210.517
5,2,4,110.925,96.360,30.792,50.704,125.868,79.000,52042,8773,47522,24966,207.364
6,2,5,144.124,118.919,43.304,66.371,153.368,0.000,46573,33597,48269,20973,263.043
7,2,6,119.379,113.870,38.584,85.961,124.413,15.709,35033,26278,56665,18502,248.958
8,3,2,218.856,124.381,33.973,148.274,162.044,1.054,66612,19461,103376,10458,344.291
9,3,3,146.518,101.045,36.399,43.306,168.723,865.000,58224,7742,82395,11948,248.428
10,3,4,178.433,102.793,45.706,111.036,124.678,194.000,47046,17299,108719,15560,281.420
11,3,5,145.865,91.180,43.851,66.277,133.440,6.523,66910,17768,36693,29046,243.568
12,3,6,170.566,114.412,43.339,136.434,128.405,23.200,32529,34002,78153,31949,308.178
13,4,2,220.343,141.406,46.241,120.865,196.296,1.653,34878,32905,117137,29188,363.402
14,4,3,193.768,141.854,56.519,136.709,143.644,1.250,57858,23956,101048,30134,336.872
15,4,4,122.736,124.256,56.167,78.101,112.724,0.000,52321,10046,62799,24233,246.992
16,4,5,144.051,158.408,51.660,92.272,164.948,6.421,47167,6440,91784,15973,308.880
17,4,6,105.415,108.688,47.717,71.474,113.935,19.023,42737,26020,27873,17600,233.126
18,5,2,240.660,163.720,59.135,157.681,187.564,0.000,39273,32917,155617,9203,404.380
19,1,3,131.067,166.649,90.476,80.509,127.575,844.000,60543,19141,78378,73839,298.560
20,1,4,130.129,98.927,42.904,43.962,142.383,193.000,54760,9163,29874,46992,229.249
21,1,5,123.286,103.551,47.331,72.444,116.529,9.467,48732,21196,47793,47574,236.304
22,1,6,190.816,87.629,32.077,127.358,137.739,18.729,46368,36798,92701,31098,297.174
23,2,2,266.741,141.437,58.721,139.034,211.646,1.223,58081,43333,135314,29716,409.401
24,2,3,123.143,106.083,36.017,75.813,119.205,1.809,45340,22109,55584,29803,231.035
25,2,4,148.139,85.310,35.576,79.997,123.253,5.377,59686,14188,67617,32319,238.826
26,2,5,118.552,100.417,54.401,75.613,105.584,16.629,40423,24682,47563,35314,235.598
27,2,6,146.959,95.153,37.656,59.907,144.549,0.000,50908,45733,43930,28998,242.112
28,3,2,299.770,133.375,57.810,236.248,196.732,57.645,71772,57756,159373,29160,490.790
29,3,3,151.341,131.788,43.359,89.382,156.916,6.528,53573,42638,62732,32386,289.657
30,3,4,206.206,92.160,45.555,148.718,104.186,93.000,49110,36904,126632,33237,298.459
31,3,5,170.868,131.463,45.550,120.548,157.505,21.272,42534,79556,50433,36483,323.603
32,4,3,435.304,181.149,67.884,267.342,281.227,0.000,64867,210508,177229,30514,616.453
33,4,4,235.106,110.874,70.376,154.242,121.417,55.000,23257,163452,63699,33805,346.035
34,4,5,168.179,125.119,71.068,100.544,136.033,14.347,28072,95989,50763,55445,307.645
35,4,6,172.783,77.371,64.137,109.062,80.648,3.693,46321,66498,61593,31625,253.847
36,5,2,381.768,140.041,118.178,260.632,152.134,9.135,34236,194216,136035,47601,530.944
37,5,3,221.438,111.392,51.199,124.660,157.500,529.000,39964,136119,66745,31031,333.359
38,5,4,193.957,111.859,47.002,99.892,159.462,540.000,59179,94460,54772,34616,306.356
39,1,6,275.076,121.697,109.888,131.165,175.777,20.057,37906,138536,85378,14020,416.830
40,2,2,252.298,150.708,77.388,154.863,182.936,12.181,32133,69093,169088,12516,415.187
41,2,3,165.472,102.530,46.295,96.870,124.837,0.000,48458,43112,72840,11304,268.002
42,2,4,126.030,108.055,53.366,69.150,111.987,418.000,42201,13736,70191,16710,234.503
43,2,5,112.246,106.641,47.399,77.610,109.715,15.837,35316,25876,38646,13989,234.724
44,2,6,123.302,94.315,48.081,72.826,109.157,12.447,43284,30138,52112,12632,230.064
45,3,2,187.810,167.455,59.042,130.098,168.254,2.129,37817,36445,103567,10443,357.394
46,3,3,119.863,139.383,44.809,99.072,115.365,0.000,54584,17242,59231,12543,259.246
47,3,4,127.805,114.813,39.025,110.740,94.470,1.617,33366,21103,84558,16683,244.235
48,3,5,120.629,112.703,39.600,240.922,122.085,169.275,37387,20246,63778,13886,402.607
49,3,6,130.465,105.273,57.467,88.462,109.132,19.323,27200,41713,59513,12260,255.061
50,4,2,222.282,120.324,41.418,135.189,165.999,0.000,39446,29290,154144,10811,342.606
51,4,3,150.257,116.959,34.193,115.536,118.911,1.424,51346,19782,89704,12182,268.640
52,4,4,96.494,87.294,32.653,81.576,74.372,4.813,34631,22420,49644,15390,188.601
53,4,5,89.526,99.756,51.985,51.930,98.107,12.740,31850,32150,21573,13807,202.022
54,4,6,134.425,79.084,36.748,71.353,105.408,0.000,33970,28701,65199,11023,213.509
55,5,2,158.716,158.133,59.131,92.639,165.079,0.000,32027,33282,128269,9287,316.849
56,5,3,150.784,133.069,54.224,115.746,116.442,2.559,51235,34421,87708,11354,286.412
57,5,4,193.534,109.639,58.378,142.382,102.687,274.000,28364,88404,91367,15003,303.447
58,5,5,196.555,108.395,76.763,96.478,131.709,0.000,37011,109931,50112,12957,304.950
59,5,6,192.116,121.106,107.568,121.152,103.180,18.678,27328,108072,56015,10690,331.900

In [17]:
x_data=data['Week of the month (first week, second, third, fourth or fifth week','Day of the week (Monday to Friday)',
           'Non-urgent order','Urgent order','Order type A','Order type B','Order type C','Fiscal sector orders','Fiscal sector orders',
            'Orders from the traffic controller sector',
            'Banking orders (1)','Banking orders (2)']

KeyError: ('Week of the month (first week, second, third, fourth or fifth week', 'Day of the week (Monday to Friday)', 'Non-urgent order', 'Urgent order', 'Order type A', 'Order type B', 'Order type C', 'Fiscal sector orders', 'Fiscal sector orders', 'Orders from the traffic controller sector', 'Banking orders (1)', 'Banking orders (2)')